baseline: ctgan
dataset_name: census_income
multiclass: false
bias_pct: null
da_pct: 0.01433
dp_protected_col: sex
minority_id: 0
majority_id: 1
third_id: null
real_data_size: 3000
seeds:
- 42
- 0
- 1
- 2
- 3
use_pca: false
pca_components: 10
ffnn:
  hidden_sizes:
  - 32
  - 16
  learning_rate: 0.001
  batch_size: 64
  epochs: 20
ctgan:
  n_synthetic: 2000
