dataset_name: census_income
da_pct: 0.01433
bias_pct: null
minority_id: 0
majority_id: 1
dp_protected_col: sex
real_data_size: 3000
seeds:
- 0
- 1
- 2
- 3
- 42
use_pca: true
pca_components: 10
multiclass: false
ffnn:
  hidden_sizes:
  - 32
  - 16
  learning_rate: 0.001
  batch_size: 64
  epochs: 20
  optimizer: adam
baseline: group_dro
